# Site settings
title: AsyncDisplayKit
description: Smooth asynchronous user interfaces for iOS apps.
baseurl: ""
url: "http://asyncdisplaykit.org"

# Build settings
highlighter: pygments
markdown: redcarpet

exclude:
- README.md
- build.sh
